media: assets/images
content:
  - name: articles
    label: Articles
    path: _posts
    type: collection
    fields: 
      - { name: category, label: Category, type: string, required: true, default: [misc] }