media: assets/images
content:
  - name: articles
    label: Articles
    path: _posts
    type: collection
    fields: 
      - { name: title, label: Title, type: string, required: true }
      - { name: author, label: Author, type: string, required: true }
      - { name: category, label: Category, type: string, required: true, default: [misc] }
      - { name: image, label: Image, type: image, required: true }
      - { name: date, label: Date, type: date, required: false }
      - { name: body, label: Body, type: rich-text, required: true }