# Site
name: 'CSArtisan'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/newspaperstaging' 
email: 'wowthemesnet@gmail.com'
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sophiabrunet:
      name:           "Sophia Brunet"
      site:           
      avatar:         
      bio:            "Head Editor, Club Manager"
      email:          
      twitter:    

    octaviaroberts:
      name:           "Octavia Roberts"
      site:           https://riso.gay
      avatar:         
      bio:            "Art Direction, Web Development"
      email:          
    
    sevanazadoian:
      name:           "Sevana Zadoian"          
      avatar:         
      bio:            "Author"
      email:             
    
    ivykim:
      name:           "Ivy Kim"
      bio:            "Author"

      

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: CSArtisan
      avatar: /assets/images/iconblack.svg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

#baseurl
baseurl: /newspaperstaging

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]