# ↓ Site
name: 'CSArtisan'
description: 'Get the latest on CSArts Performances, Events, Updates, & More, or play the Weekly Mini Crossword!'
logo: 'assets/images/thumbnail.png'
# favicon: 'assets/images/favicon.ico'
baseurl: '' 
email: 'csartsnewspaper@gmail.com'
# mailchimp-list:

future: true

include: ["_pages"]
permalink: /:title/

# Promo Banner
# !! Banner only appears if there is content within bannercontent !!
bannercontent: "Follow us on Instagram!"
bannerlink: "https://instagram.com/csartsnewspaper"

url: "https://csartisan.org"

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  # ↑ installed by template
  # ↓ installed by user
  - jekyll-admin   
  - jekyll-minifier

# Defaults
defaults:

  # ↓ all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: 
      avatar: 
      
  # ↓ all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 11

# baseurl
baseurl: 

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]